### PR TITLE
Rebuild romio

### PR DESCRIPTION
**Pull request by wangshilong**
PR-repos-el7: daos@PR-6752
PR-repos-el8: daos@PR-6752
PR-repos-leap15: daos@PR-6752

### CODE REVIEW

**Comment by wangshilong** [comment]
@brianjmurrell This build failed as:

RPM build errors:
error: Bad file: /builddir/build/SOURCES/packaged-runtests-leap15.patch: No such file or directory
    Bad file: /builddir/build/SOURCES/packaged-runtests-leap15.patch: No such file or directory

Shall we update source tar file?

**Comment by brianjmurrell** [comment]
> @brianjmurrell This build failed as:
> 
> RPM build errors: error: Bad file: /builddir/build/SOURCES/packaged-runtests-leap15.patch: No such file or directory Bad file: /builddir/build/SOURCES/packaged-runtests-leap15.patch: No such file or directory

I pushed a commit to fix that.  It builds now.

**Comment by wangshilong** [comment]
@brianjmurrell  there is no leap15 build RPMS, and i changed commit log a bit, it looks it failed..

**Comment by johannlombardi** [comment]
Talking with Mohamad, it sounds like this one is not required.

**Review by brianjmurrell — APPROVED** [review]

**Pull request merged**
